# Generated by Django 3.1.7 on 2021-03-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('bocal_1', models.CharField(max_length=5)),
                ('bocal_2', models.CharField(max_length=5)),
                ('bocal_3', models.CharField(max_length=5)),
                ('bocal_4', models.CharField(max_length=5)),
                ('bocal_5', models.CharField(max_length=5)),
                ('bocal_6', models.CharField(max_length=5)),
                ('bocal_7', models.CharField(max_length=5)),
                ('bocal_8', models.CharField(max_length=5)),
                ('bocal_9', models.CharField(max_length=5)),
                ('bocal_10', models.CharField(max_length=5)),
                ('bocal_11', models.CharField(max_length=5)),
                ('bocal_12', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Nozzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
