# Generated by Django 3.1.7 on 2021-03-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nozzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzle',
            name='Magazine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nozzle.magazine'),
            preserve_default=False,
        ),
    ]
