# Generated by Django 3.1.7 on 2021-03-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nozzle', '0003_auto_20210322_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nozzle',
            name='magazine',
        ),
        migrations.AddField(
            model_name='magazine',
            name='nozzle',
            field=models.ManyToManyField(to='nozzle.Nozzle'),
        ),
    ]
