# Generated by Django 3.1.7 on 2021-03-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nozzle', '0004_auto_20210322_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=10)),
                ('loc_1', models.CharField(max_length=1)),
                ('loc_2', models.CharField(max_length=1)),
                ('loc_3', models.CharField(max_length=1)),
                ('loc_4', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='nozzle',
        ),
        migrations.AlterField(
            model_name='magazine',
            name='bocal_1',
            field=models.CharField(choices=[('901', '901'), ('902', '902'), ('904', '904'), ('913', '913'), ('915', '915'), ('917', '917'), ('918', '918'), ('919', '919'), ('920', '920'), ('932', '932'), ('933', '933'), ('935', '935'), ('936', '936'), ('937', '937'), ('938', '938'), ('939', '939')], max_length=5),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='bocal_10',
            field=models.CharField(choices=[('901', '901'), ('902', '902'), ('904', '904'), ('913', '913'), ('915', '915'), ('917', '917'), ('918', '918'), ('919', '919'), ('920', '920'), ('932', '932'), ('933', '933'), ('935', '935'), ('936', '936'), ('937', '937'), ('938', '938'), ('939', '939')], max_length=5),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='bocal_11',
            field=models.CharField(choices=[('901', '901'), ('902', '902'), ('904', '904'), ('913', '913'), ('915', '915'), ('917', '917'), ('918', '918'), ('919', '919'), ('920', '920'), ('932', '932'), ('933', '933'), ('935', '935'), ('936', '936'), ('937', '937'), ('938', '938'), ('939', '939')], max_length=5),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='bocal_12',
            field=models.CharField(choices=[('901', '901'), ('902', '902'), ('904', '904'), ('913', '913'), ('915', '915'), ('917', '917'), ('918', '918'), ('919', '919'), ('920', '920'), ('932', '932'), ('933', '933'), ('935', '935'), ('936', '936'), ('937', '937'), ('938', '938'), ('939', '939')], max_length=5),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='bocal_2',
            field=models.CharField(choices=[('901', '901'), ('902', '902'), ('904', '904'), ('913', '913'), ('915', '915'), ('917', '917'), ('918', '918'), ('919', '919'), ('920', '920'), ('932', '932'), ('933', '933'), ('935', '935'), ('936', '936'), ('937', '937'), ('938', '938'), ('939', '939')], max_length=5),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='bocal_3',
            field=models.CharField(choices=[('901', '901'), ('902', '902'), ('904', '904'), ('913', '913'), ('915', '915'), ('917', '917'), ('918', '918'), ('919', '919'), ('920', '920'), ('932', '932'), ('933', '933'), ('935', '935'), ('936', '936'), ('937', '937'), ('938', '938'), ('939', '939')], max_length=5),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='bocal_4',
            field=models.CharField(choices=[('901', '901'), ('902', '902'), ('904', '904'), ('913', '913'), ('915', '915'), ('917', '917'), ('918', '918'), ('919', '919'), ('920', '920'), ('932', '932'), ('933', '933'), ('935', '935'), ('936', '936'), ('937', '937'), ('938', '938'), ('939', '939')], max_length=5),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='bocal_5',
            field=models.CharField(choices=[('901', '901'), ('902', '902'), ('904', '904'), ('913', '913'), ('915', '915'), ('917', '917'), ('918', '918'), ('919', '919'), ('920', '920'), ('932', '932'), ('933', '933'), ('935', '935'), ('936', '936'), ('937', '937'), ('938', '938'), ('939', '939')], max_length=5),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='bocal_6',
            field=models.CharField(choices=[('901', '901'), ('902', '902'), ('904', '904'), ('913', '913'), ('915', '915'), ('917', '917'), ('918', '918'), ('919', '919'), ('920', '920'), ('932', '932'), ('933', '933'), ('935', '935'), ('936', '936'), ('937', '937'), ('938', '938'), ('939', '939')], max_length=5),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='bocal_7',
            field=models.CharField(choices=[('901', '901'), ('902', '902'), ('904', '904'), ('913', '913'), ('915', '915'), ('917', '917'), ('918', '918'), ('919', '919'), ('920', '920'), ('932', '932'), ('933', '933'), ('935', '935'), ('936', '936'), ('937', '937'), ('938', '938'), ('939', '939')], max_length=5),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='bocal_8',
            field=models.CharField(choices=[('901', '901'), ('902', '902'), ('904', '904'), ('913', '913'), ('915', '915'), ('917', '917'), ('918', '918'), ('919', '919'), ('920', '920'), ('932', '932'), ('933', '933'), ('935', '935'), ('936', '936'), ('937', '937'), ('938', '938'), ('939', '939')], max_length=5),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='bocal_9',
            field=models.CharField(choices=[('901', '901'), ('902', '902'), ('904', '904'), ('913', '913'), ('915', '915'), ('917', '917'), ('918', '918'), ('919', '919'), ('920', '920'), ('932', '932'), ('933', '933'), ('935', '935'), ('936', '936'), ('937', '937'), ('938', '938'), ('939', '939')], max_length=5),
        ),
    ]
