# Generated by Django 3.1.7 on 2021-03-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nozzle', '0008_auto_20210324_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='linha',
            new_name='linhas',
        ),
    ]
